### PR TITLE
README improvements

### PR DESCRIPTION
**Pull request by mklement0**
* Formatting carefully tweaked so that it renders nicely as a man page, on GitHub, and when producing HTML files.
* Installation instructions added.
* Example added.
* Various other small enhancements.

### CODE REVIEW

**Comment by mklement0** [comment]
The challenge is to find a _single format_ that works well with *all* 3 likely display scenarios:

* via `man`
* direct rendering of the Markdown source on GitHub
* explicitly generated HTML pages with `marked-man --html`

The PR uses headings rather than an unordered list to enumerate options, which makes it easy to write multi-paragraph option descriptions.

I've since discovered a way to make it work with unordered lists as well: the trick is to end each list item itself with two spaces to prevent gluing of subsequent lines directly to it on GitHub / in HTML output.

A trickier aspect is attaching more than 1 paragraph to a list item; the only workaround I've found is to:

*  end the previous paragraph's line with two spaces
* insert `&nbsp;` followed by two spaces in order to simulate a blank line without losing the association of the following lines with the same list item.

I'm happy to amend the PR, if the list format is preferred.

**Comment by kapouer** [comment]
@mklement0 indeed, the list format is preferred, and don't you think markdown to roff is better achieved with https://help.github.com/articles/writing-on-github/#newlines ? (that's --breaks option).
Does it avoid that ugly two-eol-spaces trick ?  I've been myself very annoyed by that.

(Thank you for this PR)

**Comment by mklement0** [comment]
OK, I've switched to list format.

Unfortunately, using `--breaks` is _not_ an option, if you want the output to look good in all 3 display scenarios (`man`, direct rendering on GitHub, explicitly generated HTML documents).

If all 3 display scenarios must be supported, my workaround is the best approach that I'm aware of, sadly.

If you agree, then it's probably worth documenting that in the README as well.

**Comment by mklement0** [comment]
@kapouer Any thoughts? I really think you should update the README to give people a better sense of what your great project does and to help get them started. I'm happy to tweak further based on your feedback.

Also, assuming marked-man is the successor to [your ronn npm package](https://www.npmjs.com/package/ronn), I encourage you to mark the latter as deprecated (or at least clarify how the 2 projects relate to each other).

**Comment by kapouer** [comment]
I just published a short notice at the top of ronnjs's README, it's true i only ever thought about github's project as the main landing page.
Merged your PR. Thank you for the time spent on this.

**Comment by mklement0** [comment]
@kapouer My pleasure; thanks for merging.

Re ronnjs: the one-line description on GitHub doesn't show in the npm registry in general, and in your particular case the npm page doesn't link back to your GitHub repo, presumably because you use the key `repositories` rather than `repository` in the `package.json` file.
Perhaps you could add the deprecation notice to the top of the `README.md` document itself.

**Pull request merged**
